# Number of CPUs to be allocated to the virtual machine.
cpu: 8

# Size of the disk in GiB to be allocated to the virtual machine.
disk: 60

# Amount of memory in GiB to be allocated to the virtual machine.
memory: 4

# Architecture of the virtual machine (host, x86_64, or aarch64).
# NOTE: this cannot be changed after the virtual machine is created.
arch: host

# Container runtime to be used (docker, containerd).
#
# NOTE: value cannot be changed after virtual machine is created.
# Default: docker
runtime: "docker"

# Virtual machine type (qemu or vz).
# The VZ virtualization framework requires macOS 13.
# NOTE: this cannot be changed after the virtual machine is created.
vmType: vz

# Use Rosetta for amd64 emulation (requires an Apple Silicon Mac and vmType `vz`).
rosetta: true

# Volume mount driver for the virtual machine (virtiofs, 9p, or sshfs).
# virtiofs is limited to macOS and vmType `vz`. It is the fastest of the options.
# NOTE: this cannot be changed after the virtual machine is created.
mountType: virtiofs
