name: Update Submodule

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true # Ensures the submodule is checked out

      - name: Update .argc-completions submodule
        run: |
          cd .argc-completions
          git pull origin master
          cd ..
          git config --global user.email "stephmills468@gmail.com"
          git config --global user.name "Stephen Mills"
          git add .argc-completions
          git commit -m "Update .argc-completions submodule"
          git push
